/* try {
    let x = noExiste()
} catch (error) {
    alert(error)
} */


try {
               //se puede querer disparar errores cuando el sistema no los contempla.
    throw "Error de programa"
} catch (error) {
    alert(error)
}


